export interface HubSpotHeader {
  header: string
  contentType: string[]
  category: 'Recommended' | 'Additional'
  isReadOnly: boolean
  dataType: string
  inAppEdit: boolean
  filters: boolean
}

export const HUBSPOT_HEADERS: HubSpotHeader[] = [
  // Authors
  {
    header: 'avatar',
    contentType: ['Authors'],
    category: 'Additional',
    isReadOnly: false,
    dataType: 'string',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'bio',
    contentType: ['Authors'],
    category: 'Additional',
    isReadOnly: false,
    dataType: 'string',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'displayName',
    contentType: ['Authors'],
    category: 'Recommended',
    isReadOnly: false,
    dataType: 'string',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'email',
    contentType: ['Authors'],
    category: 'Recommended',
    isReadOnly: false,
    dataType: 'string',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'facebook',
    contentType: ['Authors'],
    category: 'Recommended',
    isReadOnly: false,
    dataType: 'string',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'fullName',
    contentType: ['Authors'],
    category: 'Recommended',
    isReadOnly: false,
    dataType: 'string',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'linkedin',
    contentType: ['Authors'],
    category: 'Recommended',
    isReadOnly: false,
    dataType: 'string',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'twitter',
    contentType: ['Authors'],
    category: 'Recommended',
    isReadOnly: false,
    dataType: 'string',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'website',
    contentType: ['Authors'],
    category: 'Recommended',
    isReadOnly: false,
    dataType: 'string',
    inAppEdit: false,
    filters: false,
  },

  // Website Pages
  {
    header: 'headHtml',
    contentType: ['Website Pages'],
    category: 'Recommended',
    isReadOnly: false,
    dataType: 'string',
    inAppEdit: false,
    filters: false,
  },

  // Landing Pages
  {
    header: 'campaign',
    contentType: ['Landing Pages'],
    category: 'Additional',
    isReadOnly: false,
    dataType: 'string',
    inAppEdit: true,
    filters: false,
  },
  {
    header: 'pageExpiryEnabled',
    contentType: ['Landing Pages'],
    category: 'Additional',
    isReadOnly: false,
    dataType: 'boolean',
    inAppEdit: true,
    filters: false,
  },

  // Website Pages & Landing Pages
  {
    header: 'templatePath',
    contentType: ['Website Pages', 'Landing Pages'],
    category: 'Additional',
    isReadOnly: false,
    dataType: 'string',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'pageRedirected',
    contentType: ['Website Pages', 'Landing Pages'],
    category: 'Additional',
    isReadOnly: true,
    dataType: 'boolean',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'subcategory',
    contentType: ['Website Pages', 'Landing Pages'],
    category: 'Additional',
    isReadOnly: true,
    dataType: 'string',
    inAppEdit: true,
    filters: false,
  },

  // Blog Postss
  {
    header: 'postBody',
    contentType: ['Blog Posts'],
    category: 'Additional',
    isReadOnly: false,
    dataType: 'string',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'archivedAt',
    contentType: ['Blog Posts'],
    category: 'Additional',
    isReadOnly: true,
    dataType: 'number',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'contentGroupId',
    contentType: ['Blog Posts'],
    category: 'Additional',
    isReadOnly: true,
    dataType: 'string',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'currentlyPublished',
    contentType: ['Blog Posts'],
    category: 'Additional',
    isReadOnly: true,
    dataType: 'boolean',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'postSummary',
    contentType: ['Blog Posts'],
    category: 'Additional',
    isReadOnly: true,
    dataType: 'string',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'rssBody',
    contentType: ['Blog Posts'],
    category: 'Additional',
    isReadOnly: true,
    dataType: 'string',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'rssSummary',
    contentType: ['Blog Posts'],
    category: 'Additional',
    isReadOnly: true,
    dataType: 'string',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'blogAuthorId',
    contentType: ['Blog Posts'],
    category: 'Recommended',
    isReadOnly: false,
    dataType: 'string',
    inAppEdit: true,
    filters: false,
  },
  {
    header: 'enableGoogleAmpOutputOverride',
    contentType: ['Blog Posts'],
    category: 'Additional',
    isReadOnly: false,
    dataType: 'boolean',
    inAppEdit: true,
    filters: false,
  },
  {
    header: 'tagIds',
    contentType: ['Blog Posts'],
    category: 'Recommended',
    isReadOnly: false,
    dataType: 'array',
    inAppEdit: true,
    filters: true,
  },

  // Website Pages & Blog Postss
  {
    header: 'linkRelCanonicalUrl',
    contentType: ['Website Pages', 'Blog Posts'],
    category: 'Recommended',
    isReadOnly: false,
    dataType: 'string',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'metaDescription',
    contentType: ['Website Pages', 'Blog Posts'],
    category: 'Recommended',
    isReadOnly: false,
    dataType: 'string',
    inAppEdit: false,
    filters: true,
  },

  // Website Pages, Landing Pages & Blog Postss
  {
    header: 'attachedStylesheets',
    contentType: ['Website Pages', 'Landing Pages', 'Blog Posts'],
    category: 'Additional',
    isReadOnly: false,
    dataType: 'array',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'featuredImage',
    contentType: ['Website Pages', 'Landing Pages', 'Blog Posts'],
    category: 'Additional',
    isReadOnly: false,
    dataType: 'string',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'featuredImageAltText',
    contentType: ['Website Pages', 'Landing Pages', 'Blog Posts'],
    category: 'Recommended',
    isReadOnly: false,
    dataType: 'string',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'widgets',
    contentType: ['Website Pages', 'Landing Pages', 'Blog Posts'],
    category: 'Additional',
    isReadOnly: false,
    dataType: 'object',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'authorName',
    contentType: ['Website Pages', 'Landing Pages', 'Blog Posts'],
    category: 'Additional',
    isReadOnly: true,
    dataType: 'string',
    inAppEdit: false,
    filters: true,
  },
  {
    header: 'categoryId',
    contentType: ['Website Pages', 'Landing Pages', 'Blog Posts'],
    category: 'Additional',
    isReadOnly: true,
    dataType: 'number',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'contentTypeCategory',
    contentType: ['Website Pages', 'Landing Pages', 'Blog Posts'],
    category: 'Additional',
    isReadOnly: true,
    dataType: 'number',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'currentState',
    contentType: ['Website Pages', 'Landing Pages', 'Blog Posts'],
    category: 'Recommended',
    isReadOnly: true,
    dataType: 'string',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'layoutSections',
    contentType: ['Website Pages', 'Landing Pages', 'Blog Posts'],
    category: 'Additional',
    isReadOnly: true,
    dataType: 'object',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'translations',
    contentType: ['Website Pages', 'Landing Pages', 'Blog Posts'],
    category: 'Additional',
    isReadOnly: true,
    dataType: 'object',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'updatedById',
    contentType: ['Website Pages', 'Landing Pages', 'Blog Posts'],
    category: 'Additional',
    isReadOnly: true,
    dataType: 'string',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'url',
    contentType: ['Website Pages', 'Landing Pages', 'Blog Posts'],
    category: 'Additional',
    isReadOnly: true,
    dataType: 'string',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'widgetContainers',
    contentType: ['Website Pages', 'Landing Pages', 'Blog Posts'],
    category: 'Additional',
    isReadOnly: true,
    dataType: 'object',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'archivedInDashboard',
    contentType: ['Website Pages', 'Landing Pages', 'Blog Posts'],
    category: 'Recommended',
    isReadOnly: false,
    dataType: 'boolean',
    inAppEdit: true,
    filters: false,
  },
  {
    header: 'domain',
    contentType: ['Website Pages', 'Landing Pages', 'Blog Posts'],
    category: 'Recommended',
    isReadOnly: false,
    dataType: 'string',
    inAppEdit: true,
    filters: true,
  },
  {
    header: 'publishDate',
    contentType: ['Website Pages', 'Landing Pages', 'Blog Posts'],
    category: 'Recommended',
    isReadOnly: false,
    dataType: 'date-time',
    inAppEdit: true,
    filters: false,
  },
  {
    header: 'state',
    contentType: ['Website Pages', 'Landing Pages', 'Blog Posts'],
    category: 'Recommended',
    isReadOnly: false,
    dataType: 'string',
    inAppEdit: true,
    filters: true,
  },
  {
    header: 'useFeaturedImage',
    contentType: ['Website Pages', 'Landing Pages', 'Blog Posts'],
    category: 'Additional',
    isReadOnly: false,
    dataType: 'boolean',
    inAppEdit: true,
    filters: false,
  },

  // Blogs
  {
    header: 'absoluteUrl',
    contentType: ['Blogs'],
    category: 'Additional',
    isReadOnly: false,
    dataType: 'string',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'description',
    contentType: ['Blogs'],
    category: 'Recommended',
    isReadOnly: false,
    dataType: 'string',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'publicTitle',
    contentType: ['Blogs'],
    category: 'Recommended',
    isReadOnly: false,
    dataType: 'string',
    inAppEdit: false,
    filters: true,
  },
  {
    header: 'listingPageId',
    contentType: ['Blogs'],
    category: 'Additional',
    isReadOnly: true,
    dataType: 'string',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'allowComments',
    contentType: ['Blogs'],
    category: 'Additional',
    isReadOnly: false,
    dataType: 'boolean',
    inAppEdit: true,
    filters: false,
  },

  // Website Pages, Landing Pages, Blog Postss & Blogs
  {
    header: 'htmlTitle',
    contentType: ['Website Pages', 'Landing Pages', 'Blog Posts', 'Blogs'],
    category: 'Recommended',
    isReadOnly: false,
    dataType: 'string',
    inAppEdit: false,
    filters: true,
  },
  {
    header: 'publicAccessRules',
    contentType: ['Website Pages', 'Landing Pages', 'Blog Posts', 'Blogs'],
    category: 'Additional',
    isReadOnly: false,
    dataType: 'array',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'publicAccessRulesEnabled',
    contentType: ['Website Pages', 'Landing Pages', 'Blog Posts', 'Blogs'],
    category: 'Additional',
    isReadOnly: true,
    dataType: 'boolean',
    inAppEdit: false,
    filters: false,
  },

  // Website Pages, Landing Pages, Blog Postss & Tags
  {
    header: 'createdById',
    contentType: ['Website Pages', 'Landing Pages', 'Blog Posts', 'Tags'],
    category: 'Additional',
    isReadOnly: true,
    dataType: 'string',
    inAppEdit: false,
    filters: false,
  },

  // Blogs, Tags & Authors
  {
    header: 'deletedAt',
    contentType: ['Blogs', 'Tags', 'Authors'],
    category: 'Additional',
    isReadOnly: true,
    dataType: 'date-time',
    inAppEdit: false,
    filters: false,
  },

  // Blog Postss, Blogs, Tags & Authors
  {
    header: 'created',
    contentType: ['Blog Posts', 'Blogs', 'Tags', 'Authors'],
    category: 'Additional',
    isReadOnly: true,
    dataType: 'date-time',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'updated',
    contentType: ['Blog Posts', 'Blogs', 'Tags', 'Authors'],
    category: 'Additional',
    isReadOnly: true,
    dataType: 'date-time',
    inAppEdit: false,
    filters: false,
  },

  // Website Pages, Blog Postss, Blogs, Tags & Authors
  {
    header: 'language',
    contentType: ['Website Pages', 'Blog Posts', 'Blogs', 'Tags', 'Authors', 'Landing Pages'],
    category: 'Recommended',
    isReadOnly: false,
    dataType: 'string',
    inAppEdit: true,
    filters: true,
  },

  // Website Pages, Landing Pages, Blog Postss, Blogs, Tags & Authors
  {
    header: 'slug',
    contentType: ['Website Pages', 'Landing Pages', 'Blog Posts', 'Blogs', 'Tags', 'Authors'],
    category: 'Recommended',
    isReadOnly: false,
    dataType: 'string',
    inAppEdit: false,
    filters: true,
  },

  // URL Redirects
  {
    header: 'destination',
    contentType: ['URL Redirects'],
    category: 'Recommended',
    isReadOnly: false,
    dataType: 'string',
    inAppEdit: false,
    filters: true,
  },
  {
    header: 'routePrefix',
    contentType: ['URL Redirects'],
    category: 'Recommended',
    isReadOnly: false,
    dataType: 'string',
    inAppEdit: false,
    filters: true,
  },
  {
    header: 'isMatchFullUrl',
    contentType: ['URL Redirects'],
    category: 'Recommended',
    isReadOnly: false,
    dataType: 'boolean',
    inAppEdit: true,
    filters: false,
  },
  {
    header: 'isMatchQueryString',
    contentType: ['URL Redirects'],
    category: 'Recommended',
    isReadOnly: false,
    dataType: 'boolean',
    inAppEdit: true,
    filters: false,
  },
  {
    header: 'isOnlyAfterNotFound',
    contentType: ['URL Redirects'],
    category: 'Recommended',
    isReadOnly: false,
    dataType: 'boolean',
    inAppEdit: true,
    filters: false,
  },
  {
    header: 'isPattern',
    contentType: ['URL Redirects', 'Authors'],
    category: 'Recommended',
    isReadOnly: false,
    dataType: 'boolean',
    inAppEdit: true,
    filters: false,
  },
  {
    header: 'isProtocolAgnostic',
    contentType: ['URL Redirects'],
    category: 'Recommended',
    isReadOnly: false,
    dataType: 'boolean',
    inAppEdit: true,
    filters: false,
  },
  {
    header: 'isTrailingSlashOptional',
    contentType: ['URL Redirects'],
    category: 'Recommended',
    isReadOnly: false,
    dataType: 'boolean',
    inAppEdit: true,
    filters: false,
  },
  {
    header: 'precedence',
    contentType: ['URL Redirects'],
    category: 'Recommended',
    isReadOnly: false,
    dataType: 'number',
    inAppEdit: true,
    filters: false,
  },
  {
    header: 'redirectStyle',
    contentType: ['URL Redirects'],
    category: 'Recommended',
    isReadOnly: false,
    dataType: 'number',
    inAppEdit: true,
    filters: true,
  },

  // HubDB Tables
  {
    header: 'columns',
    contentType: ['HubDB Tables'],
    category: 'Additional',
    isReadOnly: false,
    dataType: 'array',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'archived',
    contentType: ['HubDB Tables'],
    category: 'Recommended',
    isReadOnly: true,
    dataType: 'boolean',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'assignedCount',
    contentType: ['HubDB Tables'],
    category: 'Additional',
    isReadOnly: true,
    dataType: 'number',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'columnCount',
    contentType: ['HubDB Tables'],
    category: 'Additional',
    isReadOnly: true,
    dataType: 'number',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'cosObjectType',
    contentType: ['HubDB Tables'],
    category: 'Additional',
    isReadOnly: true,
    dataType: 'string',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'createdById',
    contentType: ['HubDB Tables'],
    category: 'Additional',
    isReadOnly: true,
    dataType: 'number',
    inAppEdit: false,
    filters: true,
  },
  {
    header: 'crmObjectTypeId',
    contentType: ['HubDB Tables'],
    category: 'Additional',
    isReadOnly: true,
    dataType: 'number',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'hasUnpublishedRowChanges',
    contentType: ['HubDB Tables'],
    category: 'Additional',
    isReadOnly: true,
    dataType: 'boolean',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'label',
    contentType: ['HubDB Tables'],
    category: 'Additional',
    isReadOnly: true,
    dataType: 'string',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'partitioningSettings',
    contentType: ['HubDB Tables'],
    category: 'Additional',
    isReadOnly: true,
    dataType: 'object',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'portalId',
    contentType: ['HubDB Tables'],
    category: 'Additional',
    isReadOnly: true,
    dataType: 'number',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'publishedAt',
    contentType: ['HubDB Tables'],
    category: 'Additional',
    isReadOnly: true,
    dataType: 'date-time',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'rowCount',
    contentType: ['HubDB Tables'],
    category: 'Additional',
    isReadOnly: true,
    dataType: 'number',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'updated',
    contentType: ['HubDB Tables'],
    category: 'Additional',
    isReadOnly: true,
    dataType: 'number',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'updatedBy',
    contentType: ['HubDB Tables'],
    category: 'Additional',
    isReadOnly: true,
    dataType: 'object',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'updatedById',
    contentType: ['HubDB Tables'],
    category: 'Additional',
    isReadOnly: true,
    dataType: 'number',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'allowChildTables',
    contentType: ['HubDB Tables'],
    category: 'Additional',
    isReadOnly: false,
    dataType: 'boolean',
    inAppEdit: true,
    filters: false,
  },
  {
    header: 'allowPublicApiAccess',
    contentType: ['HubDB Tables'],
    category: 'Additional',
    isReadOnly: false,
    dataType: 'boolean',
    inAppEdit: true,
    filters: false,
  },
  {
    header: 'dynamicMetaTags',
    contentType: ['HubDB Tables'],
    category: 'Additional',
    isReadOnly: false,
    dataType: 'object',
    inAppEdit: true,
    filters: false,
  },
  {
    header: 'enableChildTablePages',
    contentType: ['HubDB Tables'],
    category: 'Additional',
    isReadOnly: false,
    dataType: 'boolean',
    inAppEdit: true,
    filters: false,
  },
  {
    header: 'useForPages',
    contentType: ['HubDB Tables'],
    category: 'Additional',
    isReadOnly: false,
    dataType: 'boolean',
    inAppEdit: true,
    filters: false,
  },

  // Website Pages, Landing Pages & HubDB Tables
  {
    header: 'archivedAt',
    contentType: ['Website Pages', 'Landing Pages', 'HubDB Tables'],
    category: 'Additional',
    isReadOnly: true,
    dataType: 'date-time',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'published',
    contentType: ['Website Pages', 'Landing Pages', 'HubDB Tables'],
    category: 'Additional',
    isReadOnly: true,
    dataType: 'boolean',
    inAppEdit: false,
    filters: false,
  },

  // Website Pages, Landing Pages, URL Redirects & HubDB Tables
  {
    header: 'createdAt',
    contentType: ['Website Pages', 'Landing Pages', 'URL Redirects', 'HubDB Tables'],
    category: 'Additional',
    isReadOnly: true,
    dataType: 'date-time',
    inAppEdit: false,
    filters: false,
  },
  {
    header: 'updatedAt',
    contentType: ['Website Pages', 'Landing Pages', 'URL Redirects', 'HubDB Tables'],
    category: 'Additional',
    isReadOnly: true,
    dataType: 'date-time',
    inAppEdit: false,
    filters: false,
  },

  // All content types
  {
    header: 'name',
    contentType: [
      'Website Pages',
      'Landing Pages',
      'Blog Posts',
      'Blogs',
      'Tags',
      'Authors',
      'HubDB Tables',
    ],
    category: 'Recommended',
    isReadOnly: false,
    dataType: 'string',
    inAppEdit: false,
    filters: true,
  },
  {
    header: 'id',
    contentType: [
      'Website Pages',
      'Landing Pages',
      'Blog Posts',
      'Blogs',
      'Tags',
      'Authors',
      'URL Redirects',
      'HubDB Tables',
    ],
    category: 'Recommended',
    isReadOnly: true,
    dataType: 'string',
    inAppEdit: false,
    filters: false,
  },
]
